---
- name: Remove rsyslog v5
  yum: name='rsyslog-5*' state=absent
  tags: [ "syslog" , "yum" , "packages" ]

- name: Install rsysog repo
  copy:
    src: rsyslogall.repo
    dest: /etc/yum.repos.d/rsyslogall.repo
    owner: root
    group: root
    mode: 0644
  tags: [ "config" , "syslog" ]

- name: Install rsyslog v7 and other packages
  yum: name={{ item }} state=present
  with_items:
    - rsyslog-7*
    - cronie
    - cronie-anacron
    - crontabs
    - gnutls-utils
    - rsyslog-gnutls
  tags: [ "syslog" , "yum" , "packages" ]

- name: Copy main rsylog collector config
  template:
    src: main_logger.conf.j2
    dest: /etc/rsyslog.d/main_logger.conf
    owner: root
    group: root
    mode: 0644
  tags: [ "config" , "syslog" , "mainconf" , "syslogssl" ]
  notify: restart rsyslog

- name: Copy SSL cert
  template:
    src: rsyslog_ssl_crt.j2
    dest: "{{ rsyslog_ssl_crt_path }}/{{ rsyslog_ssl_filename }}.crt"
    owner: root
    group: root
    mode: 0644
  when: rsyslog_encrypt
  tags: [ "config" , "syslog" , "syslogssl" ]

- name: Copy SSL key
  template:
    src: rsyslog_ssl_key.j2
    dest: "{{ rsyslog_ssl_key_path }}/{{ rsyslog_ssl_filename }}.key"
    owner: root
    group: root
    mode: 0400
  when: rsyslog_encrypt
  tags: [ "config" , "syslog" , "syslogssl" ]

- name: Setup cron job to delete old postfix logs from MTAs
  cron:
    name: "delete old postfix logs from MTAs"
    state: absent
    user: root
    hour: 12
    minute: 05
    job: 'find /var/log/remote/mta* \( -name "postfix*.log*" -or -name "dkim*.log*" \) -and -mtime +3 | xargs rm'
  tags: [ "cron" , "syslog" ]

- name: Setup cron job to compress old remote logs
  cron:
    name: "compress old remote logs"
    state: present
    user: root
    hour: 01
    minute: 30
    job: "find /var/log/remote -type f -name \"*.log\" -mtime +2 | xargs gzip"
  tags: [ "cron" , "syslog" ]

- name: Setup cron job to delete old remote logs
  cron:
    name: "delete old compressed logs"
    state: present
    user: root
    hour: 02
    minute: 10
    job: "find /var/log/remote -type f -name \"*.log.gz\" -mtime +180 | xargs rm"
  tags: [ "cron" , "syslog" ]
