---
- name: remove rsyslog v5
  yum: name='rsyslog-5*' state=absent
  tags: [ "syslog" , "yum" , "packages" ]

- name: install rsysog repo
  copy: src=rsyslogall.repo
        dest=/etc/yum.repos.d/rsyslogall.repo
        owner=root
        group=root
        mode=0644
  tags: [ "config" , "syslog" ]

- name: install rsyslog v7 and other packages
  yum: name={{ item }} state=present
  with_items:
    - rsyslog-7*
    - cronie
    - cronie-anacron
    - crontabs
    - gnutls-utils
    - rsyslog-gnutls
  tags: [ "syslog" , "yum" , "packages" ]

- name: copy main rsylog collector config
  template: src=main_logger.conf.j2
            dest=/etc/rsyslog.d/main_logger.conf
            owner=root
            group=root
            mode=0644
  tags: [ "config" , "syslog" ]
  notify: restart rsyslog

- name: setup cron job to compress old remote logs
  cron: name="compress old remote logs"
        state=present
        user=root
        hour=01
        minute=10
        job="find /var/log/remote -type f -name \"*.log\" -mtime +7 | xargs gzip"
  tags: [ "cron" , "syslog" ]

- name: setup cron job to delete old remote logs
  cron: name="delete old compressed logs"
        state=present
        user=root
        hour=02
        minute=10
        job="find /var/log/remote -type f -name \"*.log.gz\" -mtime +180 | xargs rm"
  tags: [ "cron" , "syslog" ]
