---
- name: install rsyslog
  yum: name=rsyslog-5.10* state=latest
  tags: syslog

- name: Start and enable rsyslog
  service: name=rsyslog state=started enabled=yes
  tags: syslog

- name: Create /var/lib/rsyslog
  file: path=/var/lib/rsyslog state=directory owner=root group=root mode=700
  tags: syslog

- name: Set rsyslog options
  lineinfile: dest=/etc/sysconfig/rsyslog regexp='^SYSLOGD_OPTIONS' line='SYSLOGD_OPTIONS="-c 5"'
  tags: syslog

- name: copy rsyslog.conf
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.conf
  tags: syslog