---
- name: Register output of hostname -f
  command: hostname -f
  register: hostname_check
  tags: syslog
  changed_when: false
  always_run: true

- name: Check for valid fqdn
  fail: msg='Hostname does not match ansible_fqdn'
  when: hostname_check.stdout != ansible_fqdn
  tags: syslog

- name: Check for localhost in fqdn
  fail: msg='localhost in hostname'
  when: "'localhost' in hostname_check.stdout or 'localhost' in ansible_fqdn"
  tags: syslog

- {include: collector.yml, when: '"syslog_collector" in group_names'}
- {include: relay.yml, when: '"syslog_relay" in group_names'}

# Define package lists which are different for major versions of Red Hat
- include: setup-RedHat-5.yml
  when: ansible_distribution_major_version | int == 5
  tags: syslog

- include: setup-RedHat-6.yml
  when: ansible_distribution_major_version | int == 6
  tags: syslog

- name: Create yum shell script for updating rsyslog
  template:
    src: rsyslog-update.j2
    dest: /tmp/rsyslog-update
    owner: root
    group: root
    mode: 0644
  tags: syslog

- name: Install new rsyslog packages
  command: yum shell -y /tmp/rsyslog-update
  tags: syslog

- name: Remove yum shell script
  file:
    path: /tmp/rsyslog-update
    state: absent
  tags: syslog

- name: Create /var/log/buffer
  file:
    path: /var/log/buffer
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: syslog

- name: Preserve fqdn when shipping logs
  lineinfile:
    state: present
    dest: /etc/rsyslog.conf
    insertafter: '^#### GLOBAL DIRECTIVES'
    line: '$PreserveFQDN on'
  notify: restart rsyslog
  tags: syslog

- name: Check imfile_groups.logpath for logs to monitor
  stat:
    path: "{{ item.logpath }}"
    get_md5: no
  register: logcheck
  with_items: imfile_groups
  tags: [ 'syslog' , 'slconf']

- name: Copy main rsyslog shipper config
  template:
    src: shipper.conf.j2
    dest: /etc/rsyslog.d/shipper.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  when: '"syslog_collector" not in group_names and "syslog_relay" not in group_names'
  tags: [ 'syslog' , 'slconf' ]

- name: Start and enable rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: started
  tags: syslog
