---
- name: Install packages for TLS encryption
  yum: name={{ item }} state=present
  with_items:
    - gnutls-utils
    - rsyslog-gnutls
  tags: [ "syslog" , "yum" ]

- {include: collector.yml, when: '"syslog_collector" in group_names'}
- {include: relay.yml, when: '"syslog_relay" in group_names'}

- name: Copy main rsyslog shipper config
  template: src=shipper.conf.j2 dest=/etc/rsyslog.d/shipper.conf owner=root group=root mode=0644
  notify: restart rsyslog
  tags: [ "syslog" , "config" , "slcc" ]
