---
- name: Install packages for TLS encryption
  yum: name={{ item }} state=present
  with_items:
    - gnutls-utils
    - rsyslog-gnutls
  tags: [ "syslog" , "yum" ]

- {include: collector.yml, when: '"syslog_collector" in group_names'}
- {include: relay.yml, when: '"syslog_relay" in group_names'}
- {include: convert-sysklog.yml, when: 'ansible_os_family == "RedHat" and ansible_distribution_version|int >= 5 and ansible_distribution_version|int < 6'}

- name: Copy main rsyslog shipper config
  template: src=shipper.conf.j2 dest=/etc/rsyslog.d/shipper.conf owner=root group=root mode=0644
  notify: restart rsyslog
  when: '"syslog_collector" not in group_names and "syslog_relay" not in group_names'
  tags: [ "syslog" , "config" , "slcc" ]
