---
- name: register output of hostname -f
  command: hostname -f
  register: hostname_check
  tags: syslog

- name: check for valid fqdn
  fail: msg='Hostname does not match ansible_fqdn'
  when: hostname_check.stdout != ansible_fqdn
  tags: syslog

- name: check for localhost in fqdn
  fail: msg='localhost in hostname'
  when: "'localhost' in hostname_check.stdout or 'localhost' in ansible_fqdn"
  tags: syslog

- {include: collector.yml, when: '"syslog_collector" in group_names'}
- {include: relay.yml, when: '"syslog_relay" in group_names'}
- {include: convert-sysklog.yml, when: 'ansible_os_family == "RedHat" and ansible_distribution_version|int >= 5 and ansible_distribution_version|int < 6'}

- name: install rsyslog packages
  yum: name={{ item }} state=present
  with_items:
    - rsyslog-5.10*
    - gnutls-utils
    - rsyslog-gnutls
  tags: syslog

- name: preserve fqdn when shipping logs
  lineinfile: "state=present dest=/etc/rsyslog.conf insertafter='^#### GLOBAL DIRECTIVES' line='$PreserveFQDN on'"
  notify: restart rsyslog
  tags: test

- name: copy main rsyslog shipper config
  template: src=shipper.conf.j2 dest=/etc/rsyslog.d/shipper.conf owner=root group=root mode=0644
  notify: restart rsyslog
  when: '"syslog_collector" not in group_names and "syslog_relay" not in group_names'
  tags: [ "syslog" , "slcc" ]

- name: start and enable rsyslog
  service: name=rsyslog enabled=yes state=started
  tags: syslog