---
- name: Copy main rsyslog relay config
  template: src=listener.conf.j2
            dest=/etc/rsyslog.d/listener.conf
            owner=root
            group=root
            mode=0644
  notify: restart rsyslog
  tags: [ "syslog" , "config" , "relay" ]