---
- name: Define package list (Red Hat 5)
  set_fact:
    syslog_packages_install:
      - rsyslog5
      - rsyslog5-gnutls
      - gnutls-utils
    syslog_packages_remove:
      - rsyslog
      - sysklogd
